name: TP iCal Filter
on:
  schedule:
    - cron: "0 * * * *"    # hver time
  workflow_dispatch:

permissions:
  contents: write          # må ha skrivetilgang for å pushe til main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run filter
        env:
          TP_ICAL_URL: ${{ secrets.TP_ICAL_URL }}
        run: python tp_filter.py

      - name: Publish filtered.ics to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main          # <- viktig: publiser til main
          publish_dir: .                # filen filtered.ics ligger i repo-roten
          destination_dir: .            # legg den i roten
          enable_jekyll: false
          commit_message: "chore: publish filtered.ics [skip ci]"
